version: '3'
networks:
  network-zabbix:
    name: network-zabbix
    ipam:
      driver: default
      config:
        - subnet: "172.0.18.0/24"  
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbixuserpassword
    restart: always
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-trunk
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbixuserpassword
      - ZBX_SERVER=zabbix-server
      - ZBX_SERVER_PORT=10051
      - ZBX_SERVER_NAME=zabbix-server
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-trunk
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbixuserpassword
      - PHP_TZ=Europe/Berlin
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
      - ZBX_SERVER_NAME=zabbix-server
    volumes:
      - www:/usr/share
      - letsencrypt:/etc/letsencrypt
      - apache2:/etc/apache2
    depends_on:
      - mysql

volumes: 
  mysql:
    external: true
  www:
    external: true
  apache2:
    external: true
  letsencrypt:
    external: true 
